### ISSUE TITLE
회원 API 개편

### ISSUE THREAD

**Issue by onezerokang** [road-maker/road-maker-spring#292]
## Overview

현재 회원 API 설계는 RESTful 원칙을 벗어나며, 레이어 간 책임이 명확하지 않아 유지보수가 어렵다. 회원 API를 RESTful 원칙에 부합하게 변경하고, 더욱 깔끔하고 유지보수하기 쉬운 구조를 만들고자 합니다.

## Todo

- [x] 공통
  - [x] Spring RestDocs를 이용하여 API 문서 작성
  - [x] API에 동사를 제거하고 HTTP Method로 표현하기
- [x] 회원가입 API 개편 - POST /api/auth/signup
- [x] 로그인 API 개편 - POST /api/auth/login
- [x] 회원 정보 조회 API 개편 - GET /api/members/{memberId}
- [x] 회원 정보 수정 API 개편 - PATCH /api/members/profile
- [x] 회원 프로필 사진 등록 API 개편 - POST /api/members/profile/avatar
